version: "3.8"

services:

  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.8
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - ./grafana/datasources:/etc/grafana/provisioning/datasources
     - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - grafana-network

networks:
 grafana-network: